# Generated by Django 4.2.7 on 2025-07-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
